### ISSUE TITLE
Problem with load resources

### ISSUE THREAD

**Issue by ItsShock** [microsoft/PowerVirtualAgentsSamples#91]
Hi, when running index.html on live server I get such errors in the console:

Failed to load resource: the server responded with a status of 404 (Not Found)  :5500/api/directline/token:1 

Error: Failed to fetch JSON due to 404   index.html:242 
at fetchJSON (index.html:136:17)
at async main (index.html:229:27)
(anonymous) @ index.html:242

Does anyone know what this may be about?

**Comment by ItsShock** [comment]
When i run 2.location-and-file-uploading by npm start , now i get

TypeError: Cannot set property closed of #<Readable> which has only a getter
    at patch (C:\Users\domia\Desktop\czatbot\PowerVirtualAgentsSamples\BuildYourOwnCanvasSamples\2.location-and-file-uploading\web\node_modules\restify\lib\request.js:848:30)
    at Object.<anonymous> (C:\Users\domia\Desktop\czatbot\PowerVirtualAgentsSamples\BuildYourOwnCanvasSamples\2.location-and-file-uploading\web\node_modules\restify\lib\server.js:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.nodeDevHook [as .js] (C:\Users\domia\Desktop\czatbot\PowerVirtualAgentsSamples\BuildYourOwnCanvasSamples\2.location-and-file-uploading\web\node_modules\node-dev\lib\hook.js:61:7)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\domia\Desktop\czatbot\PowerVirtualAgentsSamples\BuildYourOwnCanvasSamples\2.location-and-file-uploading\web\node_modules\restify\lib\index.js:10:14)
(node:14796) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by ItsShock** [comment]
using an older version of node solved the problem

**Comment by ItsShock** [comment]
using an older version of node solved the problem
